apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentient-ai.fullname" . }}-ollama
  labels:
    {{- include "sentient-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: 11434
      protocol: TCP
      name: ollama
  selector:
    app.kubernetes.io/name: {{ include "sentient-ai.name" . }}-ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
